baseURL = 'https://gohugo.io/'
languageCode = 'en-us'
theme = "nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "Hello"
hostname = "gohugo.io"
  [params.author]
    name = "May Hnin Phyu"   # Website and RSS feed author
    email = "May.mayhninphyu95@gmail.com"  # RSS feed email address
    mainSections = ["post"]



readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"
target = "_blank"
aria = "GitHub Profile"


[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/may-hninphyu/"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "email"
url = "May.mayhninphyu95@gmail.com"
aria = "My e-Mail Address"
